name: CI/CD corporativ-bot

# Триггер на пуш в main ветку
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: pip install --upgrade pip
      - run: pip install -r requirements.txt

      # 4. Проверка базового запуска бота (тест)
      - name: Run bot test
        run: |
          python -c "from bot import main; print('Bot module imports successfully')"

      # 5. (Опционально) Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t corporativ-bot .
